services:
  - type: web
    name: jobadmin-backend
    env: docker
    plan: free
    rootDir: JobManagementAPI
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/JobManagementAPI.dll
